### ISSUE TITLE
End to end test failing in CI with error about protobuf

### ISSUE THREAD

**Issue by gth828r** [gth828r/brownify#34]
We are seeing the following error:
```txt
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/brownify", line 5, in <module>
    from brownify.cli import main
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownify/cli.py", line 10, in <module>
    from brownify.runners import PipelineProcessor
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownify/runners.py", line 14, in <module>
    from brownify.splitters import AudioSplitter
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownify/splitters.py", line 6, in <module>
    from spleeter.separator import Separator
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/spleeter/separator.py", line 26, in <module>
    import tensorflow as tf
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

The protobuf version being installed in CI is 3.9.x, which is well behind 3.19.0. See if we can fix this error.

**Comment by gth828r** [comment]
My locally installed version is 3.19.3, and I tried forcing the package through setup.cfg to use that version. That seems to have done the trick. I could have just forced the protobuf version to be higher than 3.19.0, but that would be inconsistent with what I have done for other dependencies. Then again, this is really not my dependency to manage (I'm not sure why it is breaking in the first place).

I think I'll open up an issue to track this in the longer term.
